services:
  backend:
    build: ./backend # Path to the backend Dockerfile
    ports:
      - "9090:9090" # Exposes backend on port 9090
    environment:
      - SPRING_PROFILES_ACTIVE=dev # Optional: Set Spring profiles (e.g., dev, prod)
    networks:
      - app-network

  frontend:
    build: ./frontend/my-vue-app # Path to the frontend Dockerfile
    ports:
      - "8080:8080" # Exposes frontend on port 8080
    depends_on:
      - backend # Makes sure frontend waits for the backend
    networks:
      - app-network
    volumes:
      - ./frontend/my-vue-app:/app
 

networks:
  app-network: # Creates a network for the frontend and backend to communicate
    driver: bridge
